spring:
  application:
    name: demo-spring-cloud-vault
  cloud:
    vault:
      authentication: token
      token: s.sEqhOP0BD5cVXUtjWf2srkBp
      host: 134.209.180.102
      port: 8200
      scheme: http
      enabled: true
      kv:
        backend: secret
        profile-separator: '/'
        default-context: cc-global
spring.config.import: vault://, vault://secret/certificates
management:
  health:
    vault:
      enabled: true

PropertyCamino: ${camino}